
CREATE TABLE artista (
dni VARCHAR2(10) CONSTRAINT PK_arti PRIMARY KEY,
nombre VARCHAR2(30) NOT NULL);

CREATE TABLE `musica`.`GRUPO` (
  `cod` CHAR(3) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `fecha` DATE NULL,
  `pais` VARCHAR(45) NULL,
  PRIMARY KEY (`cod`));

CREATE TABLE club (
cod CHAR(3) CONSTRAINT PK_club PRIMARY KEY,
nombre VARCHAR2(30) NOT NULL,
sede VARCHAR2(30),
num NUMBER(6),
cod_gru CHAR(3) NOT NULL CONSTRAINT FK_club_grupo REFERENCES grupo (cod));

CREATE TABLE companhia (
cod CHAR(3) CONSTRAINT PK_compa PRIMARY KEY,
nombre VARCHAR2(30) NOT NULL,
dir VARCHAR2(30),
fax VARCHAR2(15),
tfno VARCHAR2(15) );


CREATE TABLE cancion (
cod NUMBER(3) CONSTRAINT PK_can PRIMARY KEY,
titulo VARCHAR2(30) NOT NULL,
duracion NUMBER(2) );
--CREATE TABLE CANCION ( cod CHAR(3), titulo VARCHAR(30) NOT NULL, duracion INT(4), PRIMARY KEY (cod) )

CREATE TABLE disco (
cod CHAR(3) CONSTRAINT PK_dis PRIMARY KEY,
nombre VARCHAR2(30),
fecha DATE ,
cod_comp CHAR(3) NOT NULL CONSTRAINT FK_disco_comp REFERENCES companhia (cod),
cod_gru CHAR(3) NOT NULL CONSTRAINT FK_disco_grupo REFERENCES grupo (cod));
--CREATE TABLE DISCO ( cod CHAR(3), nombre VARCHAR(30), fecha DATE, cod_comp CHAR(3), cod_gru CHAR(3), PRIMARY KEY (cod), FOREIGN KEY (cod_comp) REFERENCES COMPANHIA(cod), FOREIGN KEY (cod_gru) REFERENCES GRUPO(cod) )

CREATE TABLE esta (
can NUMBER(3) CONSTRAINT FK_esta_can REFERENCES cancion (cod),
cod CHAR(3) CONSTRAINT FK_esta_disco REFERENCES disco (cod),
CONSTRAINT PK_esta PRIMARY KEY (can, cod));
--CREATE TABLE esta ( can CHAR(3), cod CHAR(3), FOREIGN KEY (can) REFERENCES CANCION(cod), FOREIGN KEY (cod) REFERENCES DISCO(cod))

CREATE TABLE pertenece (
dni VARCHAR(10),
cod CHAR(3),
funcion VARCHAR(45),
    FOREIGN KEY (dni) REFERENCES ARTISTA(dni),
    FOREIGN KEY (cod) REFERENCES GRUPO(cod)
    );
